# Reusable publish workflow for open-source NPM packages
#   - dual publication (to NPM, then GitHub)
#   - single package per repo (no mono-repo support)
name: publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Build Distributables
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: package.json
          path: package.json
      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

  publish-github:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - uses: actions/download-artifact@v2
        with:
          name: package.json
      - uses: actions/download-artifact@v2
        with:
          name: lib
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # publish-npmjs:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: package.json
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: lib
  #     - name: Establish NPM Scope
  #       run: |
  #         jq --arg name '@appfolio/react-gears-cypress' '.name = $name' package.json > package.json.tmp && mv package.json.tmp package.json
  #     - name: Publish to NPM
  #       run: |
  #         touch $HOME/.npmrc
  #         chmod 0600 $HOME/.npmrc
  #         cat << EOF > ~/.npmrc
  #         //registry.npmjs.org/:_authToken=${NPM_TOKEN}
  #         @appfolio:registry=https://registry.npmjs.org/
  #         EOF
  #         npm publish
  #       env:
  #         NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
